# Generated by Django 5.0.1 on 2026-04-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_categor_7dfe8a_idx',
            old_name='products_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_created_a77fb9_idx',
            old_name='products_created_idx',
        ),
    ]
