# Generated by Django 5.0.1 on 2026-04-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_convers_3ebb41_idx',
            old_name='messages_conv_created_idx',
        ),
    ]
