# Generated by Django 5.0.1 on 2026-04-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bid',
            new_name='bids_auction_5cbac0_idx',
            old_name='bids_auction_amount_idx',
        ),
    ]
