# Generated by Django 5.0.1 on 2026-04-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useragent',
            new_name='user_agents_target__2384b6_idx',
            old_name='user_agents_target_idx',
        ),
    ]
